import { ProductShot } from "../product-shot";

// Visual proof for the comparison / alternatives pages: the same two real
// dashboard captures the landing uses (regenerated by capture-product-shots.mjs
// so they never drift from the shipped UI). Shared here so every comparison page
// shows the product, not just prose about it.
//
// It renders no section or padding of its own: the caller drops it inside a
// <Band>, which owns the band's tone and rhythm. That is what lets the same
// block sit on graphite here and on paper elsewhere without a second variant.
export function ProductProof({ lead }: { lead?: string }) {
  return (
    <>
      <div className="lp-head">
        <h2>
          This is what you actually{" "}
          <span className="lp-serif-accent">get</span>.
        </h2>
        <p>
          {lead ??
            "No mockups. Every competitor move (pricing, product, hiring) lands in one place: scored by severity, explained in plain English, and ready to act on."}
        </p>
      </div>
      <div className="mt-10 grid gap-6 lg:grid-cols-2 lg:items-start">
        <ProductShot
          src="/product/overview.webp"
          alt="Outrival dashboard overview: KPI tiles for total signals with a trend sparkline, critical signals pending, and active competitors, above a feed of recent competitor signals spanning pricing, product, hiring, funding and content."
          width={2240}
          height={1626}
          sizes="(min-width: 1024px) 540px, 100vw"
          caption="Your overview: every competitor, ranked by what moved."
        />
        <ProductShot
          src="/product/signal-detail.webp"
          alt="A single Outrival signal in detail: a critical pricing alert that a competitor cut its Pro plan 30% to $49 a month, with the strategic insight, why it matters, the recommended action, and a before-and-after of the pricing change."
          width={1720}
          height={886}
          sizes="(min-width: 1024px) 540px, 100vw"
          caption="One signal, in full: what changed, why, and what to do."
        />
      </div>
    </>
  );
}
