import { ProductShot } from "../product-shot";

// Visual proof for the comparison / alternatives pages: the same two real
// dashboard captures the landing uses (regenerated by capture-product-shots.mjs
// so they never drift from the shipped UI). Shared here so every comparison page
// shows the product, not just prose about it.
export function ProductProof({ lead }: { lead?: string }) {
  return (
    <section className="mx-auto w-full max-w-6xl px-6 py-16 sm:py-20">
      <div className="max-w-2xl">
        <h2 className="text-2xl font-semibold leading-tight tracking-tight sm:text-3xl">
          This is what you actually get
        </h2>
        <p className="mt-4 leading-relaxed text-text-muted text-pretty">
          {lead ??
            "No mockups. Every competitor move (pricing, product, hiring) lands in one place: scored by severity, explained in plain English, and ready to act on."}
        </p>
      </div>
      <div className="mt-10 grid gap-6 lg:grid-cols-2 lg:items-start">
        <ProductShot
          src="/product/overview.webp"
          alt="Outrival dashboard overview: KPI tiles for total signals with a trend sparkline, critical signals pending, and active competitors, above a feed of recent competitor signals spanning pricing, product, hiring, funding and content."
          width={2240}
          height={1626}
          sizes="(min-width: 1024px) 540px, 100vw"
          caption="Your overview: every competitor, ranked by what moved."
        />
        <ProductShot
          src="/product/signal-detail.webp"
          alt="A single Outrival signal in detail: a critical pricing alert that a competitor cut its Pro plan 30% to $49 a month, with the strategic insight, why it matters, the recommended action, and a before-and-after of the pricing change."
          width={1720}
          height={886}
          sizes="(min-width: 1024px) 540px, 100vw"
          caption="One signal, in full: what changed, why, and what to do."
        />
      </div>
    </section>
  );
}
