import { ProductShot } from "../product-shot";

// Visual proof for the comparison / alternatives pages: one capture of the
// whole app — real sidebar, real topbar, real Overview — regenerated by
// capture-product-shots.mjs so it never drifts from the shipped UI.
//
// It was two half-width crops side by side. Those answer "what does a signal
// look like", which is the landing's question; a comparison page is asking
// "what am I actually buying instead of the tool I was quoted", and the answer
// to that is the product in one piece. The three notes underneath name what is
// on screen, so the block still says something at the size a page renders it.
//
// It renders no section or padding of its own: the caller drops it inside a
// <Band>, which owns the band's tone and rhythm. That is what lets the same
// block sit on graphite here and on paper elsewhere without a second variant.

const POINTS = [
  {
    label: "The lead signal",
    body: "The one move that matters this week, with what to do about it already written.",
  },
  {
    label: "Who moved",
    body: "Every competitor you track, ranked by how much actually changed since last week.",
  },
  {
    label: "Needs a decision",
    body: "What is still unread, by severity, so nothing important sits in the pile.",
  },
];

export function ProductProof({ lead }: { lead?: string }) {
  return (
    <>
      <div className="lp-head">
        <h2>
          This is what you actually{" "}
          <span className="lp-serif-accent">get</span>.
        </h2>
        <p>
          {lead ??
            "No mockups. This is the app, on a real week: every competitor move (pricing, product, hiring) in one place, scored by severity, explained in plain English."}
        </p>
      </div>
      <div className="lp-proof">
        <ProductShot
          src="/product/dashboard.webp"
          alt="The Outrival dashboard: a left sidebar with Overview, Signals, Digests, Activity, AI Visibility, Trends, Compare and Competitors; the Overview page showing a critical pricing signal (a competitor cut its Pro plan 30% to $49 a month) with the recommended action, a Who moved band of five competitors ranked by activity, and a Needs a decision queue of unread high-severity signals."
          width={3200}
          height={1970}
          sizes="(min-width: 1088px) 1056px, 100vw"
          caption="One week in the app: the lead signal, who moved, and what still needs a decision."
        />
        <ul className="lp-proof-points">
          {POINTS.map((p) => (
            <li key={p.label}>
              <b>{p.label}</b>
              <p>{p.body}</p>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
