import { ArrowRightIcon } from "@phosphor-icons/react/ssr";

import { ProductShot } from "./product-shot";

// "This is the product." Replaces the old From-scraped-HTML pipeline diagram at the
// same slot (after Sources): a real look beats an explanation of the mechanism. The
// two captures are the actual dashboard rendered against the sample universe
// (Vantage, Beacon, Lumen, Cobalt, Meridian) — regenerated by
// scripts/capture-product-shots.mjs so they never drift from the shipped UI. The
// width/height below are the capture's intrinsic pixels (deviceScaleFactor 2);
// `w-full h-auto` scales to the column, so the real aspect governs once loaded.

const STEPS = ["Scanned hourly", "Classified by severity", "Written as a decision"];

function Step({ label, last }: { label: string; last?: boolean }) {
  return (
    <li className="flex items-center gap-3">
      <span className="font-medium text-foreground">{label}</span>
      {!last && (
        <ArrowRightIcon className="size-3.5 shrink-0 text-text-subtle" aria-hidden />
      )}
    </li>
  );
}

export function ProductShowcase() {
  return (
    <section
      className="border-y border-border bg-background-2 py-16 sm:py-24"
      id="product"
      data-reveal
    >
      <div className="mx-auto w-full max-w-6xl px-6">
        <div className="max-w-3xl">
          <h2 className="text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">
            This is the product.
          </h2>
          <p className="mt-5 max-w-2xl leading-relaxed text-text-muted">
            No mockups. Every competitor move (pricing, product, hiring) lands in
            one place: scored by severity, explained in plain English, and ready to
            act on.
          </p>
        </div>

        {/* The mechanism in one line — what used to be the pipeline diagram. */}
        <ol className="mt-8 flex flex-wrap items-center gap-x-3 gap-y-2 text-sm text-text-muted">
          {STEPS.map((label, i) => (
            <Step key={label} label={label} last={i === STEPS.length - 1} />
          ))}
        </ol>

        <div className="mt-12 grid gap-6 lg:grid-cols-2 lg:items-start">
          <ProductShot
            src="/product/overview.webp"
            alt="Outrival dashboard overview: KPI tiles for total signals with a trend sparkline, critical signals pending, and active competitors, above a feed of recent competitor signals spanning pricing, product, hiring, funding and content."
            width={2240}
            height={1626}
            sizes="(min-width: 1024px) 540px, 100vw"
            caption="Your overview: every competitor, ranked by what moved."
          />

          <ProductShot
            src="/product/signal-detail.webp"
            alt="A single Outrival signal in detail: a critical pricing alert that Vantage cut its Pro plan 30% to $49 a month, with the strategic insight, why it matters, the recommended action, and a before-and-after of the pricing change."
            width={1720}
            height={886}
            sizes="(min-width: 1024px) 540px, 100vw"
            caption="One signal, in full: what changed, why, and what to do."
          />
        </div>
      </div>
    </section>
  );
}
