import { z } from "zod";
import { AI_CONFIG } from "../config";
import { groundedAiCall } from "../grounding/grounded-call";
import { attachQuality, type WithQuality } from "../grounding/types";

export const DigestSchema = z.object({
  temperature: z.enum(["low", "moderate", "high"]),
  tldr: z.array(z.string()).max(3),
  sections: z.array(
    z.object({
      urgency: z.enum(["action_required", "watch", "fyi"]),
      competitor: z.string(),
      category: z.string(),
      insight: z.string(),
      so_what: z.string(),
    }),
  ),
  // Sector trends (patch-13). Appended deterministically by the weekly job from
  // already-formulated sectoral_signals — NOT generated by the model here, so the
  // wording the user saw on the dashboard is preserved verbatim. Optional.
  sectoralTrends: z
    .array(z.object({ title: z.string(), insight: z.string() }))
    .optional(),
});

export type Digest = z.infer<typeof DigestSchema>;

export interface DigestInputSignal {
  competitor: string;
  category: string;
  severity: "low" | "medium" | "high" | "critical";
  insight: string;
  so_what: string | null;
}

export async function generateDigest(
  signals: DigestInputSignal[],
): Promise<WithQuality<Digest> | null> {
  const prompt = `<signals>
${JSON.stringify(signals, null, 2)}
</signals>

<task>
Generate a weekly competitive-intelligence digest from these signals.
- Assess the overall temperature (low/moderate/high)
- TL;DR: 3 key points maximum
- Group the signals: critical/high → action_required, medium → watch, low → fyi
- Write all text values in English.
Reply ONLY with valid JSON, no markdown.
</task>

<format>
{
  "temperature": "low|moderate|high",
  "tldr": ["point 1", "point 2", "point 3"],
  "sections": [
    { "urgency": "action_required|watch|fyi", "competitor": "...",
      "category": "...", "insight": "...", "so_what": "..." }
  ]
}
</format>`;

  const result = await groundedAiCall({
    taskName: "generate_digest",
    config: AI_CONFIG.digest,
    prompt,
    sourceText: JSON.stringify(signals, null, 2),
    schema: DigestSchema,
    maxTokens: 2048,
  });
  return result ? attachQuality(result.output, result.quality) : null;
}
