import { z } from "zod";
import { AI_CONFIG } from "../config";
import { groundedAiCall } from "../grounding/grounded-call";
import { attachQuality, type WithQuality } from "../grounding/types";
import type { MyProductContext } from "./insight";

export const DigestSchema = z.object({
  temperature: z.enum(["low", "moderate", "high"]),
  tldr: z.array(z.string()).max(3),
  sections: z.array(
    z.object({
      urgency: z.enum(["action_required", "watch", "fyi"]),
      competitor: z.string(),
      category: z.string(),
      insight: z.string(),
      so_what: z.string(),
      // The double-capture badge (Véracité Intelligence v2 P4). Declared here or a
      // re-parse would strip it, same reason as `signalId` below — but unlike every
      // other deterministic append this one sits INSIDE a block the model writes, so
      // the weekly job overwrites the field on every section, hit or miss. A gap the
      // model invented must never survive as proof; only the P2 ledger can badge a
      // row. Null `gapMinutes` = the two check timestamps aren't both recorded.
      verification: z.object({ gapMinutes: z.number().nullable() }).optional(),
    }),
  ),
  // Sector trends (patch-13). Appended deterministically by the weekly job from
  // already-formulated sectoral_signals — NOT generated by the model here, so the
  // wording the user saw on the dashboard is preserved verbatim. Optional.
  sectoralTrends: z
    .array(z.object({ title: z.string(), insight: z.string() }))
    .optional(),
  // Standing queries (watched Ask questions) that materially changed this week.
  // Appended deterministically by the weekly job, same pattern as sectoralTrends.
  watchedQuestions: z
    .array(z.object({ question: z.string(), changeSummary: z.string() }))
    .optional(),
  // Accumulated memory (OUT-172): what the reader knows about a competitor over the
  // WHOLE tracking period, not just this week. Built by buildCompetitorMemory
  // (@outrival/shared) from the signal history and appended after generation — the
  // model neither sees it nor writes it, so it costs no token and states no claim
  // the classifier had not already restated. Shape mirrors CompetitorStory; the
  // weekly job assigns the shared type straight in, so a drift fails to compile.
  competitorStories: z
    .array(
      z.object({
        competitorId: z.string(),
        competitor: z.string(),
        since: z.string(),
        sinceLabel: z.string(),
        total: z.number(),
        facts: z.array(
          z.object({
            category: z.string(),
            before: z.string().nullable(),
            after: z.string(),
            at: z.string(),
            ago: z.string(),
            // The signal this fact was replayed from, so the in-app reader can link
            // back to the evidence. Declared here or a re-parse would strip it.
            signalId: z.string().nullable().optional(),
          }),
        ),
      }),
    )
    .optional(),
  /** Competitors the cap left out of `competitorStories`, for a "+N more" line. */
  competitorStoriesOmitted: z.number().optional(),
});

export type Digest = z.infer<typeof DigestSchema>;

export interface DigestInputSignal {
  competitor: string;
  category: string;
  severity: "low" | "medium" | "high" | "critical";
  insight: string;
  so_what: string | null;
}

/**
 * Hard cap on the signals fed to one digest generation. Every input signal costs
 * prompt tokens AND demands an output section — past ~30 the reply outgrows
 * maxTokens, truncates mid-JSON and the whole digest parse-fails, so the busiest
 * (most engaged) org would be exactly the one whose week goes silent. The cap
 * keeps the highest-severity signals and tells the model how many were left out.
 */
export const DIGEST_MAX_SIGNALS = 30;

const SEVERITY_RANK: Record<DigestInputSignal["severity"], number> = {
  critical: 3,
  high: 2,
  medium: 1,
  low: 0,
};

/** Top DIGEST_MAX_SIGNALS by severity (ties keep input order) + how many dropped. */
export function capDigestSignals(signals: DigestInputSignal[]): {
  kept: DigestInputSignal[];
  omitted: number;
} {
  if (signals.length <= DIGEST_MAX_SIGNALS) return { kept: signals, omitted: 0 };
  const kept = signals
    .map((s, i) => ({ s, i }))
    .sort((a, b) => SEVERITY_RANK[b.s.severity] - SEVERITY_RANK[a.s.severity] || a.i - b.i)
    .slice(0, DIGEST_MAX_SIGNALS)
    .sort((a, b) => a.i - b.i)
    .map(({ s }) => s);
  return { kept, omitted: signals.length - kept.length };
}

function formatSignals(signals: DigestInputSignal[]): string {
  return JSON.stringify(signals, null, 2);
}

/**
 * The week's signals as the digest is grounded on them — same cap, same formatting
 * as the generation call. Exported so the publication gate verifies the digest's
 * claims against byte-identical source.
 */
export function digestSourceText(allSignals: DigestInputSignal[]): string {
  return formatSignals(capDigestSignals(allSignals).kept);
}

export async function generateDigest(
  allSignals: DigestInputSignal[],
  myProduct?: MyProductContext,
): Promise<WithQuality<Digest> | null> {
  const { kept: signals, omitted } = capDigestSignals(allSignals);
  const myProductBlock = myProduct
    ? `\n<my_product>
These signals are about OUR competitors. Read the week from our perspective.
Category: ${myProduct.category}
Audience: ${myProduct.audience}
Value proposition: ${myProduct.valueProp}
</my_product>\n`
    : "";
  const tldrGuidance = myProduct
    ? "TL;DR: 3 key points maximum, each framed around what it means for OUR product (threat, opportunity, or non-event)"
    : "TL;DR: 3 key points maximum";

  const omittedBlock = omitted
    ? `\n<omitted>
${omitted} lower-severity signal${omitted > 1 ? "s were" : " was"} left out of the list above for brevity. Do NOT invent their contents — at most, acknowledge the extra volume in one TL;DR point (e.g. "plus ${omitted} smaller changes").
</omitted>\n`
    : "";
  const prompt = `<signals>
${JSON.stringify(signals, null, 2)}
</signals>
${omittedBlock}${myProductBlock}
<task>
Generate a weekly competitive-intelligence digest from these signals.
- Assess the overall temperature (low/moderate/high)
- ${tldrGuidance}
- Group the signals: critical/high → action_required, medium → watch, low → fyi
- Write all text values in English.
Reply ONLY with valid JSON, no markdown.
</task>

<format>
{
  "temperature": "low|moderate|high",
  "tldr": ["point 1", "point 2", "point 3"],
  "sections": [
    { "urgency": "action_required|watch|fyi", "competitor": "...",
      "category": "...", "insight": "...", "so_what": "..." }
  ]
}
</format>`;

  const result = await groundedAiCall({
    taskName: "generate_digest",
    config: AI_CONFIG.digest,
    prompt,
    sourceText: formatSignals(signals),
    schema: DigestSchema,
    // Room for one section per capped signal plus the TL;DR — 2048 truncated the
    // JSON on busy weeks (only pay for tokens actually generated).
    maxTokens: 3072,
  });
  return result ? attachQuality(result.output, result.quality) : null;
}
