import { z } from "zod";
import { complete } from "../provider";
import { AI_CONFIG } from "../config";
import { safeParseJson } from "../lib/parse";

export const DigestSchema = z.object({
  temperature: z.enum(["low", "moderate", "high"]),
  tldr: z.array(z.string()).max(3),
  sections: z.array(
    z.object({
      urgency: z.enum(["action_required", "watch", "fyi"]),
      competitor: z.string(),
      category: z.string(),
      insight: z.string(),
      so_what: z.string(),
    }),
  ),
  // Sector trends (patch-13). Appended deterministically by the weekly job from
  // already-formulated sectoral_signals — NOT generated by the model here, so the
  // wording the user saw on the dashboard is preserved verbatim. Optional.
  sectoralTrends: z
    .array(z.object({ title: z.string(), insight: z.string() }))
    .optional(),
});

export type Digest = z.infer<typeof DigestSchema>;

export interface DigestInputSignal {
  competitor: string;
  category: string;
  severity: "low" | "medium" | "high" | "critical";
  insight: string;
  so_what: string | null;
}

export async function generateDigest(
  signals: DigestInputSignal[],
): Promise<Digest | null> {
  const prompt = `<signals>
${JSON.stringify(signals, null, 2)}
</signals>

<task>
Generate a weekly competitive-intelligence digest from these signals.
- Assess the overall temperature (low/moderate/high)
- TL;DR: 3 key points maximum
- Group the signals: critical/high → action_required, medium → watch, low → fyi
- Write all text values in English.
Reply ONLY with valid JSON, no markdown.
</task>

<format>
{
  "temperature": "low|moderate|high",
  "tldr": ["point 1", "point 2", "point 3"],
  "sections": [
    { "urgency": "action_required|watch|fyi", "competitor": "...",
      "category": "...", "insight": "...", "so_what": "..." }
  ]
}
</format>`;

  const raw = await complete(AI_CONFIG.digest, { prompt, json: true, maxTokens: 2048 });
  const result = safeParseJson(raw, DigestSchema);
  if (!result.ok) {
    console.error("Digest parse failed:", result.error, "raw:", raw.slice(0, 500));
    return null;
  }
  return result.value;
}
