import {
  pgTable,
  text,
  integer,
  jsonb,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sourceTypeEnum } from "./monitors";

// Cached, deterministic extractor per (domain, sourceType) — the "cache de parser"
// stage (patch-30). Generated once by the AI self-heal step, then replayed on
// every subsequent scrape with ZERO AI (the spec is CSS selectors + whitelisted
// transforms, run by @outrival/scrapers' replayExtractor). Validation failure on a
// replay (the site relaid out) triggers a self-heal that bumps `version`.
//
// Keyed by domain, NOT competitor: the same SaaS monitored across orgs shares one
// extractor (one generation, not N), and it survives competitor deletion. `spec`
// is left untyped here (cast to ExtractorSpec from @outrival/shared at the call
// site) to match the codebase convention for jsonb columns (cf. snapshots).
export const parserExtractors = pgTable(
  "parser_extractors",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    /** Normalized host (www-stripped), via normalizeDomain from @outrival/shared. */
    domain: text("domain").notNull(),
    sourceType: sourceTypeEnum("source_type").notNull(),
    /** ExtractorSpec (@outrival/shared): { version, list?, fields }. */
    spec: jsonb("spec").notNull(),
    /** Mirrors spec.version; the column lets us index/sort without reading jsonb. */
    version: integer("version").notNull().default(1),
    /** How many times this extractor has been regenerated by self-heal. */
    healCount: integer("heal_count").notNull().default(0),
    /** Consecutive replay validation failures — feeds the heal cooldown so a
     *  durably-broken page doesn't burn an AI call every run. */
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    /** Last time a replay of this extractor passed validation. */
    lastValidatedAt: timestamp("last_validated_at"),
    /** Last time self-heal tried to (re)generate it — drives the cooldown. */
    lastHealAttemptAt: timestamp("last_heal_attempt_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("parser_extractors_domain_source_idx").on(t.domain, t.sourceType)],
);
