import {
  URGENCY_META,
  digestGroups,
  digestHeadline,
  digestLabel,
  digestStats,
  digestSupportingPoints,
  isQuietDigest,
  quietSentence,
} from "./digest-shape";
import type { Digest } from "./api";

/**
 * A brief as Markdown, for pasting into a doc, a ticket or a Slack thread.
 *
 * The point of the export is that the brief leaves the app intact: same verdict
 * first, same decision-ordered groups, same wording. Nothing is summarized again on
 * the way out, because a second summary of a summary is where briefs start lying.
 */
export function digestToMarkdown(digest: Digest): string {
  const content = digest.content;
  const period = digest.period === "daily" ? "Daily brief" : "Competitive brief";
  const out: string[] = [`# ${period}, ${digestLabel(digest)}`, ""];

  if (isQuietDigest(content)) {
    out.push(quietSentence(content), "");
    return out.join("\n");
  }

  const headline = digestHeadline(content);
  if (headline) out.push(`> ${headline}`, "");

  const points = digestSupportingPoints(content);
  if (points.length > 0) {
    out.push(...points.map((p) => `- ${p}`), "");
  }

  const stats = digestStats(content);
  const facts = [
    `${stats.moves} move${stats.moves === 1 ? "" : "s"}`,
    `${stats.action} need${stats.action === 1 ? "s" : ""} an answer`,
    `${stats.movers.length} competitor${stats.movers.length === 1 ? "" : "s"}`,
    `activity ${content.temperature}`,
  ];
  out.push(`**${facts.join(" · ")}**`, "");

  for (const group of digestGroups(content)) {
    out.push(`## ${URGENCY_META[group.urgency].label}`, "");
    for (const s of group.items) {
      const heading = s.category ? `${s.competitor} · ${s.category}` : s.competitor;
      out.push(`### ${heading}`, "", s.insight, "");
      if (s.so_what) out.push(`→ ${s.so_what}`, "");
    }
  }

  for (const t of content.sectoralTrends ?? []) {
    out.push("## Sector trends", "", `### ${t.title}`, "", t.insight, "");
  }

  const questions = content.watchedQuestions ?? [];
  if (questions.length > 0) {
    out.push("## Your watched questions", "");
    for (const q of questions) {
      out.push(`### ${q.question}`, "", q.changeSummary, "");
    }
  }

  out.push("---", "", "Generated by Outrival · outrival.app", "");
  return out.join("\n");
}
