import type { Metadata } from "next";

// One place that gets page metadata right, because Next merges it in a way that
// is easy to get wrong twice over:
//
//   1. A page that declares no `openGraph` inherits the ROOT object verbatim —
//      including `url`, which is the homepage. Sixteen public pages were telling
//      every social crawler and every LLM that they were outrival.app.
//   2. A page that DOES declare `openGraph` replaces the root object wholesale,
//      and Next only folds in an `opengraph-image` file from the page's OWN
//      segment — not from an ancestor. So declaring og:title to fix (1) silently
//      dropped the shared social card on /about, /blog, /vs/* and /alternatives/*.
//
// Both failure modes are invisible until someone shares a link. `pageMetadata`
// always sets canonical and og:url from the same `path`, and always attaches an
// image. `scripts/check-metadata.ts` enforces it against a running site.

/** Generated by the root `app/opengraph-image.tsx` / `app/twitter-image.tsx`. */
const SHARED_OG_IMAGE = "/opengraph-image";
const SHARED_TWITTER_IMAGE = "/twitter-image";

export type PageMetadataInput = {
  /** Route path with a leading slash. Becomes both canonical and og:url. */
  path: string;
  /** The <title>. Rendered through the root "%s — Outrival" template. */
  title: string;
  /** Set when the title already reads as a full sentence and must not be suffixed. */
  titleAbsolute?: boolean;
  /** meta description, and the social description unless overridden below. */
  description: string;
  /** Social-card title, when it should read differently from the <title>. */
  socialTitle?: string;
  /** Social-card description, when the meta description is too long or too dry. */
  socialDescription?: string;
  /** Twitter title, when the card needs to read shorter than the OG one. */
  twitterTitle?: string;
  /** Twitter description, when the card needs to read shorter than the OG one. */
  twitterDescription?: string;
  /** og:type. "article" for editorial pages, "website" otherwise. */
  type?: "website" | "article";
  /**
   * Set when the route ships its own `opengraph-image.tsx` in the SAME segment
   * (today: /sample). Next merges that file itself, so `openGraph.images` is
   * left unset — but Twitter still needs it named explicitly, or the card falls
   * back to the generic site image.
   */
  ownImage?: boolean;
  /** Extra `alternates.types` entries, e.g. an RSS feed. */
  alternateTypes?: Record<string, string>;
};

export function pageMetadata(input: PageMetadataInput): Metadata {
  const {
    path,
    title,
    titleAbsolute = false,
    description,
    socialTitle = title,
    socialDescription = description,
    twitterTitle = socialTitle,
    twitterDescription = socialDescription,
    type = "website",
    ownImage = false,
    alternateTypes,
  } = input;

  const twitterImage = ownImage
    ? `${path}/opengraph-image`
    : SHARED_TWITTER_IMAGE;

  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    alternates: {
      canonical: path,
      ...(alternateTypes ? { types: alternateTypes } : {}),
    },
    openGraph: {
      type,
      url: path,
      siteName: "Outrival",
      title: socialTitle,
      description: socialDescription,
      // Omitted on purpose when the segment has its own image file.
      ...(ownImage ? {} : { images: [SHARED_OG_IMAGE] }),
    },
    twitter: {
      card: "summary_large_image",
      title: twitterTitle,
      description: twitterDescription,
      images: [twitterImage],
    },
  };
}
